### PR TITLE
Pagination position error has solved

### LINKED ISSUE #34: bug when scrolling teams page
When the team page is scrolled there is a little bug that we cannot see the very bottom of the team list.

### PR DESCRIPTION
**Pull request by SchumacherFarad**
pagination no longer overflows content

### CODE REVIEW

**Comment by Utkub24** [comment]
Hi @SchumacherFarad, thanks for the PR. Can you please update the description with pictures/videos of the page after the fix? Also explaining why the bug was happening and how the changes in this PR fixes it would be great for the team, in case we encounter a similar issue in the future. Thank you :pray: :rocket:

**Comment by SchumacherFarad** [comment]
Hi @Utkub24 , thanks for your comment. I could easily force pushed this commit as this actually does not require any review of you. But if you don't know the basics of css, I can try to explain it to you. As you can see from the commit, I just deleted the bottom:0; and position:absolute; properties of the paginator, which was the cause of the overflow because 

**absolute**

Description: The element is positioned relative to the nearest ancestor that has a position of relative, absolute, or fixed. If no such ancestor exists, it is positioned relative to the <html> element.

Attributes:

Offsets (top, right, bottom, left) are used to position the element within its containing block.

Removed from the normal document flow (does not affect sibling elements).

And as the parent of paginator is html body,  which doesn't have a specific height, it tries to fit the paginator. While doing that it may overflow due to height limitations.


Therefore, we must delete those attributes. If you have any further questions please contact me ferhatkunduraci03@gmail.com . It's better not to make these basic conversations here. Thank you for your interest.

**Comment by Utkub24** [comment]
Thanks for the slightly passive aggressive response @SchumacherFarad :pray: I believe this was a productive conversation that will help further our goals :rocket:

**Review by umut373 — COMMENTED** [review]
I read, I approved 🤓

**Comment by HuseyinSimsek7904** [comment]
> Pagination position error `has` solved

Is this intentional?

**Pull request merged**
