### PR TITLE
active player & win rate & db from scratch & average roster age

### PR DESCRIPTION
**Pull request by aliemre2023**
Screen Shot 2024-12-25 at 00 46 34

### CODE REVIEW

**Comment by aliemre2023** [comment]
Screen Shot 2024-12-26 at 01 37 31

In second commit, I prepare win rate calculation in sql, CASE and SUM operators used

**Comment by kemaltahirbicilioglu** [comment]
I do not think your win rate calculation is correct since it gives too much win rates for atlanta hawks for the year 2022. You are only joining if the team id  = home team id, but team can be away team. Also the counting logic seems not correct.

**Comment by aliemre2023** [comment]
Thanks for the warning, I fixed it

**Comment by aliemre2023** [comment]
@kemaltahirbicilioglu  prepared some validation sqls. I merged creation and validation files, this one sql file is able to create the database, but don't forget to change the attach database parts.

**Pull request merged**
